# Generated by Django 3.0.5 on 2020-04-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumb',
            new_name='storyimage',
        ),
    ]
