# Generated by Django 3.0.5 on 2020-04-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='storyimage',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
